name: Reusable - Lint

on:
  workflow_call:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install yamllint
        run: pipx install yamllint==1.38.0

      - name: Run yamllint
        run: yamllint .

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run markdownlint
        run: npx --yes markdownlint-cli2@0.22.1 "**/*.md" "#node_modules"
